'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("OrganicChemistryVisualiser.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;examples&gt;
        '''  &lt;example displayName=&quot;TNT&quot;&gt;1-methyl-2,4,6-trinitrocyclohex-1,3,5-triene&lt;/example&gt;
        '''  &lt;example displayName=&quot;Dopamine&quot;&gt;4-(2-aminoethyl)cyclohex-1,3,5-trien-1,2-diol&lt;/example&gt;&quot;
        '''  &lt;example displayName=&quot;Ibuprofen&quot;&gt;2-(4-(2-methylpropyl)cyclohex-1,3,5-triene)propan-1-oic acid&lt;/example&gt;
        '''  &lt;example displayName=&quot;Amphetamine&quot;&gt;1-cyclohex-1,3,5-trienylpropan-2-amine&lt;/example&gt;
        '''  &lt;example displayName=&quot;Citric Acid&quot;&gt;3-(1-carboxymethyl)pentan-3-ol-1,5-dioic acid&lt;/example&gt;
        '''  &lt;example displayName=&quot;Drinking Al [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property examples() As String
            Get
                Return ResourceManager.GetString("examples", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;functionalGroups&gt;
        '''  &lt;functionalGroup type=&quot;acetyl&quot;&gt;
        '''    &lt;child&gt;
        '''      &lt;representor&gt;&lt;/representor&gt;
        '''      &lt;bondType&gt;1&lt;/bondType&gt;
        '''      &lt;colour&gt;#0ea528&lt;/colour&gt;
        '''      &lt;child&gt;
        '''        &lt;representor&gt; O&lt;/representor&gt;
        '''        &lt;bondType&gt;2&lt;/bondType&gt;
        '''        &lt;colour&gt;#0ea528&lt;/colour&gt;
        '''      &lt;/child&gt;
        '''      &lt;child&gt;
        '''        &lt;representor&gt;&lt;/representor&gt;
        '''        &lt;bondType&gt;1&lt;/bondType&gt;
        '''        &lt;colour&gt;#0ea528&lt;/colour&gt;
        '''      &lt;/child&gt;
        '''    &lt;/child&gt;
        '''  &lt;/functionalGroup&gt;
        '''
        '''  &lt;functionalGroup type=&quot;fluoro&quot;&gt;
        '''    &lt;child&gt;
        '''      &lt;repre [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property functionalGroups() As String
            Get
                Return ResourceManager.GetString("functionalGroups", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!--
        '''████████╗ ██████╗ ██╗  ██╗███████╗███╗   ██╗███████╗   ██╗  ██╗███╗   ███╗██╗     
        '''╚══██╔══╝██╔═══██╗██║ ██╔╝██╔════╝████╗  ██║██╔════╝   ╚██╗██╔╝████╗ ████║██║     
        '''   ██║   ██║   ██║█████╔╝ █████╗  ██╔██╗ ██║███████╗    ╚███╔╝ ██╔████╔██║██║     
        '''   ██║   ██║   ██║██╔═██╗ ██╔══╝  ██║╚██╗██║╚════██║    ██╔██╗ ██║╚██╔╝██║██║     
        '''   ██║   ╚██████╔╝██║  ██╗███████╗██║ ╚████║███████║██╗██╔╝ ██╗██║ ╚═╝ ██║███████╗
        '''   ╚═╝    ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚══════╝╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚══════╝
        '''
        '''Tokens d [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property tokens() As String
            Get
                Return ResourceManager.GetString("tokens", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
